const vehicles = [
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge', // EV range
        petrolCapacity: 'N/A', // No fuel tank for EV
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge',
        petrolCapacity: 'N/A',
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge',
        petrolCapacity: 'N/A',
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge',
        petrolCapacity: 'N/A',
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge',
        petrolCapacity: 'N/A',
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge',
        petrolCapacity: 'N/A',
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Scorpio-N AT',
        modelYear: '2024',
        brand: 'Mahindra',
        image: 'scorpio.jpeg',
        type: 'SUV',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '15 kmpl',
        petrolCapacity: '57 L',
        price: 'Starting From ₹500/-',
        fuelType: 'Diesel',
    },
    {
        model: 'Mini Cooper Convertible',
        modelYear: '2023',
        brand: 'Mini',
        image: 'mini-cooper.jpeg',
        type: 'Car',
        transmission: 'Automatic',
        seats: '4 seats',
        mileage: '20 kmpl',
        petrolCapacity: '44 L',
        price: 'Starting From ₹400/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Self-Driving Car',
        modelYear: '2022',
        brand: 'Generic',
        image: 'volvo.png',
        type: 'Car',
        transmission: 'Manual',
        seats: '5 seats',
        mileage: '400 km/charge',
        petrolCapacity: 'N/A',
        price: 'Starting From ₹600/-',
        fuelType: 'EV',
    },
    {
        model: 'Royal Enfield Bullet',
        modelYear: '2021',
        brand: 'Royal Enfield',
        image: 'bullet.png',
        type: 'Bike',
        transmission: 'Manual',
        seats: '2 seats',
        mileage: '35 kmpl',
        petrolCapacity: '13.5 L',
        price: 'Starting From ₹300/-',
        fuelType: 'Petrol',
    },
    {
        model: 'Honda Activa',
        modelYear: '2023',
        brand: 'Honda',
        image: 'scooter.jpg',
        type: 'Bike',
        transmission: 'Automatic',
        seats: '2 seats',
        mileage: '50 kmpl',
        petrolCapacity: '5 L',
        price: 'Starting From ₹100/-',
        fuelType: 'Petrol',
    },
];

export default vehicles;